spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order-db
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  #security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/realms/e-commerce
          jwk-set-uri: http://localhost:7080/realms/e-commerce/protocol/openid-connect/certs
  kafka:
    bootstrap-servers:
      - localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

server:
  port: 8085




